Repository shinigami888/CF-CC-Questions, pull requests merged in 2022-10, with the labels that each got.

#3 best-time-to-sell.cpp
  best-time-to-sell.cpp
Labels: enhancement, hacktoberfest-accepted

#4 Writing-Faster-Code
  writing-faster-code
Labels: enhancement, hacktoberfest-accepted

#6 part 2/4
  cpp-tips-part-2.md
Labels: enhancement, hacktoberfest-accepted

#7 part 3/4
  cpp-tips-part-3.md
Labels: enhancement, hacktoberfest-accepted

#8 part 4/4
  cpp-tips-part-4.md
Labels: documentation, enhancement, hacktoberfest-accepted

#12 A2OJ-Questions-1to5
  A2OJ-Questions->1-5.cpp
Labels: enhancement, hacktoberfest-accepted

#10 added the maximum consecutive ones problem from leetcode solved in py
  max-consecutive-ones.py
Labels: hacktoberfest-accepted

#11 added a problem of leetcode
  Merge-Sorted-Array.cpp
Labels: hacktoberfest-accepted

#16 Setting up sublime text for cpp
  sublime
Labels: documentation, enhancement, hacktoberfest-accepted

#17 Big-o
  big-o notation
Labels: enhancement, hacktoberfest-accepted

#20 coding platform
  coding platforms
Labels: documentation, enhancement, hacktoberfest-accepted

#21 macros
  Macros
Labels: documentation, hacktoberfest-accepted

#22 Remove_Duplicates_From_Sorted
  Remove_Duplicates_From_Sorted.cpp
Labels: enhancement, hacktoberfest-accepted

#23 Letter_Combinations_Of_a_Phone_Number
  Letter_Combinations_Of_a_Phone_Number.cpp
Labels: enhancement, hacktoberfest-accepted

#24 Reverse_Nodes_In_K-Group
  Reverse_Nodes_In_K-Group.txt
Labels: enhancement, hacktoberfest-accepted
